baseurl = "https://blog.chilli.ai"
title = "My Internet Thoughts"
theme = "hugo-theme-cleanwhite"
languageCode = "en-GB"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true
defaultContentLanguage = "en"
enableEmoji = true
disableAliases = true
MetaDataFormat = "yaml"
showOrigin = true
# SEO options
enableRobotsTXT = true
canonifyURLs = true
timeout = 30000
pluralizeListTitles = false

#publishDir = "docs"
staticDir = "assets"

[permalinks]
  post = "/blog/:title/"

[Author]
  name = "James"
  email = "james@chilli.ai"

[outputs]
home = ["HTML", "RSS", "Algolia"]
section = [ "HTML", "RSS"]

[params]
  #readingTime = true
  ### Note: the file name and url of posts should be in lowercase ###
  header_image = "img/header.jpg"
  description = "Articles about Privacy, FOSS, Linux, and Genealogy"
  keywords = "FOSS, Linux, Privacy, Internet, Web, Genealogy, DNA"
  slogan = "(For Curious Minds)"
  SEOTitle = "blog.chilli.ai | Blog"
  #postimgfolder = "/img/postimgs" #full url: assertsDir + /img/postimgs
  image_404 = "img/404-bg.jpg"
  title_404 = "Whoops - Page Not Found :("

  # Enable to show the github link of the templete author in footer
  showOrigin = true

  # Enable to show 'about me' tag in nav bar
  about_me = true

  # algolia site search
  algolia_search = true
  algolia_appId = "3R6720J8XO"
  algolia_indexName = "blog.chilli.ai"
  algolia_apiKey = "772e02e212e43e1ea5d41e322cb72a8f"

  # Sidebar settings
  sidebar_about_description = "Curiously Minded, Open Source & Privacy Enthusiast, and Life Adventurer"
  #sidebar_avatar = "img/avatar-kz.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 1
  friends = true
  bookmarks = false

  [params.social]
  # atleast one of infooter or insidebar must be true after social url was added
  infooter       = false  # show sociae icons in footer
  insidebar      = true  # show social icons below self introduction
  rss            = true
  #linkedin       = "https://www.linkedin.com/in/kexianzhang/"
  #stackoverflow  = "https://stackoverflow.com/users/2701959/69444091"
  email          = "james@chilli.ai"
  github         = "https://github.com/jamestho"
  #zhihu         = "full profile url in facebook"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #weibo         = "full profile url in twitter"
  #instagram     = "full profile url in instagram"
  #wechat        = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  #medium        = "full profile url in medium"

  [[params.friend_link]]
  title = "The Tools We Need"
  href =  "https://thetoolsweneed.com"
  #[[params.friend_link]]
  #title = "CC的行摄日记"
  #href =  "https://www.weibo.com/u/5941049491"

  [[params.bookmark_link]]
  title =  "EVE-NG"
  href =  "http://eve-ng.net/"
  [[params.bookmark_link]]
  title =  "技术改变世界-孔今贤的博客"
  href =  "https://lingxiankong.github.io"
  [[params.bookmark_link]]
  title =  "Huabing's Blog"
  href =  "https://zhaohuabing.com"
  [[params.bookmark_link]]
  title =  "TUALATRIX's Blog"
  href =  "https://imtx.me/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "permalink", "content"]
params = ["categories", "tags"]

[blackfriday]
  hrefTargetBlank = true
  fractions = false
  nofollowLinks = true
  noreferrerLinks = true

[related]
threshold = 100
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 20
  anchor = "smart"

[sitemap]
  ChangeFreq = "daily"
  Priority = 0.5

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    simple = true
  [privacy.youtube]
    disable = true
privacyEnhanced = true
